#!/usr/bin/env bash
# script that configures an Ubuntu server with the below requirements
cp -f /etc/hosts ~/new_hosts

sed -i '/localhost/d' ~/hosts
sed -i '/facebook.com/d' ~/hosts

echo "127.0.0.2 localhost" >> ~/hosts
echo "8.8.8.8 facebook.com" >> ~/hosts
